-- User: app_user
-- DROP USER app_user;

CREATE USER app_user WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT postgres TO app_user;

ALTER USER app_user WITH PASSWORD '123456';
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app_test TO app_user;